### ISSUE TITLE
Swap X-Y axis on results charts

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/ahb-decision-support-app#11]
Give the 'economists' view.

**Comment by jrmerz** [comment]
@ncparker I added a toggle for both 'Results Page' line charts.  The default is now to have price on the Y axis.  I found did find this hard to read, so added a toggle so you can flip the axis on the fly :)  

Let me know if these charts look correct to you.

**Comment by jrmerz** [comment]
@ncparker let me know if everything looks ok.  Please reopen if there is an issue.

**Comment by ncparker** [comment]
Let's switch the default axis back to price on the x-axis.  It is much easier to read that way.  Keep the toggle for traditional economist.

**Comment by jrmerz** [comment]
Works for me :)
