### ISSUE TITLE
Transportation Geometry Routing Feature Crashing

### ISSUE THREAD

**Issue by anchowyu** [CSTARS/ahb-decision-support-app#16]
When I click the option to route transportation geometry, the model crashes.

**Comment by jrmerz** [comment]
@anchowyu How big was your run?

Just FYI, this feature still was work todo.... large scale runs (60km+ radius) will max out the browsers memory limit when you include the route geometry for each parcel.  At the moment, there is no real fix for this.... :/

**Comment by anchowyu** [comment]
Thanks for the quick response, I was definitely running 75km! :)
